#############################################
#                                           #
# Microsoft VisualStudio Code用 DockerFile  #
#                                           #
#############################################

# Debian 11.0（bullseye）を利用したnode.js
FROM node:16.13.1-bullseye-slim
RUN apt update
RUN apt install -y python3 python3-pip python3-mecab mecab-ipadic-utf8 libmecab-dev git