#############################################
#                                           #
# Microsoft VisualStudio Code用 DockerFile  #
#                                           #
#############################################

# Debian 11.0（bullseye）を利用したnode.js
FROM node:16.13.1-bullseye-slim
RUN apt update
RUN apt install -y\
    python3\
    python3-pip\
    mecab\
    python3-mecab\
    mecab-ipadic-utf8\
    libmecab-dev\
    git\
    make\
    curl\
    xz-utils\
    file\
    locales\
    sudo
RUN apt-get clean -y && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# \(ja_JP.UTF-8\)/\1/' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=ja_JP.UTF-8
RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
RUN cd mecab-ipadic-neologd && \
    ./bin/install-mecab-ipadic-neologd -n -y && \
    echo `mecab-config --dicdir`"/mecab-ipadic-neologd"